# Generated by Django 2.2.16 on 2022-06-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220604_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descriptions',
            new_name='description',
        ),
    ]
